{
	"openapi": "3.0.1",
	"info": {
		"title": "openArc - getting structured data from music games",
		"description": "openArc致力于音游机器人开发者服务，为开发者们提供统一且优质的返回格式",
		"version": "1.0"
	},
	"servers": [
		{
			"url": "https://arcapi.moezsoft.com/{version}",
			"variables": {
				"version": {
					"enum": [
						"v1",
						"v2"
					],
					"default": "v2"
				}
			}
		}
	],
	"tags": [
		{
			"name": "arcaea",
			"description": "game content endpoints for game Arcaea"
		},
		{
			"name": "arcaea-meta",
			"description": "application meta contents for game Arcaea"
		},
		{
			"name": "standard",
			"description": "basic apis for game Arcaea"
		},
		{
			"name": "forward",
			"description": "Used for online pvp"
		}
	],
	"paths": {
		"/meta/pack": {
			"summary": "Get all the pack data",
			"get": {
				"tags": [
					"arcaea"
				],
				"summary": "Get all current pack data",
				"responses": {
					"200": {
						"description": "OK",
						"content": {
							"application/json": {
								"schema": {
									"type": "array",
									"items": {
										"$ref": "#/components/schemas/Pack"
									}
								}
							},
							"application/xml": {
								"schema": {
									"type": "array",
									"items": {
										"$ref": "#/components/schemas/Pack"
									}
								}
							}
						}
					},
					"default": {
						"description": "Unknown error",
						"content": {
							"application/json": {
								"schema": {
									"$ref": "#/components/schemas/APIResult"
								}
							},
							"application/xml": {
								"schema": {
									"$ref": "#/components/schemas/APIResult"
								}
							}
						}
					}
				}
			},
			"post": {
				"tags": [
					"arcaea"
				],
				"summary": "Add new song pack to database",
				"responses": {
					"200": {
						"description": "OK",
						"content": {
							"application/json": {
								"schema": {
									"$ref": "#/components/schemas/APIResult"
								}
							},
							"application/xml": {
								"schema": {
									"$ref": "#/components/schemas/APIResult"
								}
							}
						}
					},
					"default": {
						"description": "Unknown error",
						"content": {
							"application/json": {
								"schema": {
									"$ref": "#/components/schemas/APIResult"
								}
							},
							"application/xml": {
								"schema": {
									"$ref": "#/components/schemas/APIResult"
								}
							}
						}
					}
				}
			}
		},
		"/meta/pack/{packid}": {
			"parameters": [
				{
					"in": "path",
					"name": "packid",
					"required": true,
					"schema": {
						"type": "string"
					}
				}
			],
			"summary": "Get pack data by packID",
			"get": {
				"tags": [
					"arcaea"
				],
				"summary": "Get current pack data",
				"responses": {
					"200": {
						"description": "OK",
						"content": {
							"application/json": {
								"schema": {
									"type": "object",
									"$ref": "#/components/schemas/Pack"
								}
							},
							"application/xml": {
								"schema": {
									"type": "object",
									"$ref": "#/components/schemas/Pack"
								}
							}
						}
					}
				}
			},
			"put": {
				"tags": [
					"arcaea"
				],
				"summary": "Update current song pack in database",
				"responses": {
					"200": {
						"description": "OK",
						"content": {
							"application/json": {
								"schema": {
									"$ref": "#/components/schemas/APIResult"
								}
							},
							"application/xml": {
								"schema": {
									"$ref": "#/components/schemas/APIResult"
								}
							}
						}
					},
					"default": {
						"description": "Unknown error",
						"content": {
							"application/json": {
								"schema": {
									"$ref": "#/components/schemas/APIResult"
								}
							},
							"application/xml": {
								"schema": {
									"$ref": "#/components/schemas/APIResult"
								}
							}
						}
					}
				}
			},
			"delete": {
				"tags": [
					"arcaea"
				],
				"summary": "Delete a song pack in database",
				"responses": {
					"200": {
						"description": "OK",
						"content": {
							"application/json": {
								"schema": {
									"$ref": "#/components/schemas/APIResult"
								}
							},
							"application/xml": {
								"schema": {
									"$ref": "#/components/schemas/APIResult"
								}
							}
						}
					},
					"default": {
						"description": "Unknown error",
						"content": {
							"application/json": {
								"schema": {
									"$ref": "#/components/schemas/APIResult"
								}
							},
							"application/xml": {
								"schema": {
									"$ref": "#/components/schemas/APIResult"
								}
							}
						}
					}
				}
			}
		},
		"/song": {
			"parameters": [
				{
					"$ref": "#/components/parameters/limit"
				},
				{
					"$ref": "#/components/parameters/offset"
				}
			],
			"get": {
				"tags": [
					"arcaea"
				],
				"responses": {
					"200": {
						"description": "OK",
						"content": {
							"application/json": {
								"schema": {
									"type": "array",
									"items": {
										"$ref": "#/components/schemas/Song"
									}
								}
							},
							"application/xml": {
								"schema": {
									"type": "array",
									"items": {
										"$ref": "#/components/schemas/Song"
									}
								}
							}
						}
					},
					"default": {
						"description": "Unknown error",
						"content": {
							"application/json": {
								"schema": {
									"$ref": "#/components/schemas/APIResult"
								}
							},
							"application/xml": {
								"schema": {
									"$ref": "#/components/schemas/APIResult"
								}
							}
						}
					}
				}
			}
		},
		"/song/{songid}": {
			"parameters": [
				{
					"required": true,
					"in": "path",
					"name": "songid",
					"schema": {
						"type": "string"
					}
				}
			],
			"get": {
				"tags": [
					"arcaea"
				],
				"responses": {
					"200": {
						"description": "OK"
					}
				}
			}
		},
		"/story": {
			"get": {
				"tags": [
					"arcaea"
				],
				"responses": {
					"200": {
						"description": "OK"
					}
				}
			}
		},
		"/meta/ver": {
			"summary": "Get arcapi and app version, used for further development",
			"get": {
				"tags": [
					"arcaea-meta"
				],
				"responses": {
					"200": {
						"description": "ok",
						"content": {
							"application/json": {
								"schema": {
									"type": "object",
									"properties": {
										"arcapi": {
											"$ref": "#/components/schemas/arc_api_ver"
										},
										"arcapp": {
											"$ref": "#/components/schemas/arc_ver_link"
										}
									}
								}
							},
							"application/xml": {
								"schema": {
									"type": "object",
									"properties": {
										"arcapi": {
											"$ref": "#/components/schemas/arc_api_ver"
										},
										"arcapp": {
											"$ref": "#/components/schemas/arc_ver_link"
										}
									}
								}
							}
						}
					},
					"default": {
						"description": "bad"
					}
				}
			}
		},
		"/game/userinfo": {
			"summary": "Get basic user info",
			"parameters": [
				{
					"in": "query",
					"name": "usercode",
					"required": true,
					"schema": {
						"$ref": "#/components/schemas/usercode"
					}
				},
				{
					"in": "query",
					"name": "recent",
					"required": false,
					"schema": {
						"type": "boolean",
						"nullable": true
					}
				}
			],
			"get": {
				"tags": [
					"standard"
				],
				"responses": {
					"200": {
						"$ref": "#/components/schemas/arc_user"
					},
					"default": {
						"$ref": "#/components/schemas/APIResult"
					}
				}
			}
		},
		"/game/userbest": {
			"summary": "Get user best score",
			"parameters": [
				{
					"name": "usercode",
					"in": "query",
					"required": true,
					"schema": {
						"$ref": "#/components/schemas/usercode"
					}
				},
				{
					"name": "songname",
					"in": "query",
					"required": true,
					"schema": {
						"type": "string"
					}
				},
				{
					"name": "difficulty",
					"in": "query",
					"required": true,
					"schema": {
						"$ref": "#/components/schemas/difficulty"
					}
				}
			],
			"get": {
				"tags": [
					"standard"
				],
				"responses": {
					"200": {
						"description": "ok",
						"content": {
							"application/json": {
								"schema": {
									"type": "object",
									"$ref": "#/components/schemas/best_score"
								}
							}
						}
					}
				}
			}
		},
		"/game/userbest30": {
			"summary": "Get user's best top 30 score.",
			"parameters": [
				{
					"in": "query",
					"name": "usercode",
					"required": true,
					"schema": {
						"$ref": "#/components/schemas/usercode"
					}
				}
			],
			"get": {
				"tags": [
					"standard"
				],
				"responses": {
					"200": {
						"description": "ok",
						"content": {
							"application/json": {
								"schema": {
									"type": "object",
									"properties": {
										"best30_avg": {
											"type": "number"
										},
										"recent10_avg": {
											"type": "number"
										},
										"best30_list": {
											"type": "array",
											"items": {
												"$ref": "#/components/schemas/best_score"
											},
											"maxLength": 30
										}
									}
								}
							}
						}
					}
				}
			}
		},
		"/songinfo": {
			"summary": "Get song info by name",
			"parameters": [
				{
					"in": "query",
					"required": true,
					"name": "songname",
					"schema": {
						"type": "string",
						"description": "any song name for fuzzy querying"
					}
				}
			],
			"get": {
				"tags": [
					"standard"
				],
				"responses": {
					"200": {
						"description": "ok",
						"content": {
							"application/json": {
								"schema": {
									"$ref": "#/components/schemas/Song"
								}
							},
							"application/xml": {
								"schema": {
									"$ref": "#/components/schemas/Song"
								}
							}
						}
					}
				}
			}
		},
		"/songalias": {
			"summary": "Get song id by songalias query",
			"parameters": [
				{
					"in": "query",
					"required": true,
					"name": "songname",
					"schema": {
						"type": "string",
						"description": "any song name for fuzzy querying"
					}
				}
			],
			"get": {
				"tags": [
					"standard"
				],
				"responses": {
					"200": {
						"description": "ok",
						"content": {
							"application/json": {
								"schema": {
									"type": "object",
									"properties": {
										"id": {
											"type": "string"
										}
									}
								}
							},
							"application/xml": {
								"schema": {
									"type": "object",
									"properties": {
										"id": {
											"type": "string"
										}
									}
								}
							}
						}
					}
				}
			}
		},
		"/random": {
			"summary": "Get a random song in Arcaea",
			"parameters": [
				{
					"in": "query",
					"name": "start",
					"schema": {
						"type": "number",
						"minimum": 2,
						"maximum": 23,
						"description": "range of start"
					}
				},
				{
					"in": "query",
					"name": "end",
					"schema": {
						"type": "number",
						"minimum": 2,
						"maximum": 23,
						"description": "range of end"
					}
				},
				{
					"in": "query",
					"name": "info",
					"schema": {
						"type": "boolean",
						"description": "returns song info when set true"
					}
				}
			],
			"get": {
				"tags": [
					"standard"
				],
				"responses": {
					"200": {
						"description": "ok",
						"content": {
							"application/json": {
								"schema": {
									"type": "object",
									"properties": {
										"id": {
											"type": "string"
										},
										"rating_class": {
											"type": "number",
											"enum": [
												0,
												1,
												2,
												3
											]
										},
										"song_info": {
											"$ref": "#/components/schemas/Song",
											"nullable": true
										}
									}
								}
							}
						}
					}
				}
			}
		},
		"/game/connect": {
			"summary": "Get lowest.world/connect code",
			"get": {
				"tags": [
					"standard"
				],
				"responses": {
					"200": {
						"description": "ok",
						"content": {
							"application/json": {
								"schema": {
									"type": "object",
									"properties": {
										"key": {
											"type": "string"
										}
									}
								}
							},
							"application/xml": {
								"schema": {
									"type": "object",
									"properties": {
										"key": {
											"type": "string"
										}
									}
								}
							}
						}
					}
				}
			}
		},
		"/arc/alloc": {
		},
		"/arc/forward": {
		},
		"/arc/recycle": {
		}
	},
	"components": {
		"parameters": {
			"limit": {
				"name": "limit",
				"in": "query",
				"schema": {
					"type": "number",
					"default": 5,
					"format": "int64",
					"minimum": 0
				}
			},
			"offset": {
				"name": "offset",
				"in": "query",
				"schema": {
					"type": "number",
					"default": 0,
					"format": "int64",
					"minimum": 0
				}
			},
			"filter": {
				"name": "filter",
				"in": "query",
				"schema": {
					"type": "array",
					"items": {
						"type": "string"
					}
				}
			}
		},
		"schemas": {
			"APIResult": {
				"required": [
					"status"
				],
				"type": "object",
				"properties": {
					"status": {
						"type": "number",
						"default": 0
					},
					"content": {
						"type": "object",
						"properties": {}
					}
				}
			},
			"Pack": {
				"required": [
					"id"
				],
				"type": "object",
				"properties": {
					"id": {
						"type": "string",
						"description": "曲包ID，用作唯一标识"
					},
					"plus_character": {
						"type": "integer",
						"description": "附加曲包角色"
					},
					"name_localized": {
						"type": "object",
						"description": "曲包名称本地化",
						"items": {
							"$ref": "#/components/schemas/localization"
						}
					},
					"description_localized": {
						"type": "object",
						"description": "曲包描述本地化",
						"items": {
							"$ref": "#/components/schemas/localization"
						}
					},
					"custom-banner": {
						"type": "boolean",
						"description": "未知意义",
						"default": false
					}
				}
			},
			"Song": {
				"type": "object",
				"required": [
					"id"
				],
				"properties": {
					"id": {
						"type": "string"
					},
					"title_localized": {
						"type": "object",
						"items": {
							"type": "object",
							"required": [
								"en"
							],
							"properties": {
								"en": {
									"type": "string"
								},
								"ja": {
									"type": "string",
									"nullable": true
								}
							}
						}
					},
					"artist": {
						"type": "string"
					},
					"bpm": {
						"type": "string"
					},
					"bpm_base": {
						"type": "number"
					},
					"set": {
						"type": "string"
					},
					"audioTimeSec": {
						"type": "number",
						"minimum": 0
					},
					"side": {
						"type": "number",
						"enum": [
							0,
							1
						]
					},
					"remote_dl": {
						"type": "boolean",
						"default": true
					},
					"world_unlock": {
						"type": "boolean",
						"default": false
					},
					"date": {
						"type": "number",
						"minimum": 0
					},
					"difficulties": {
						"type": "array",
						"items": {
							"type": "object",
							"properties": {
								"ratingClass": {
									"type": "number",
									"enum": [
										0,
										1,
										2,
										3
									]
								},
								"chartDesigner": {
									"type": "string"
								},
								"jacketDesigner": {
									"type": "string"
								},
								"rating": {
									"type": "number",
									"minimum": 0
								},
								"ratingReal": {
									"type": "number",
									"minimum": 0
								},
								"ratingPlus": {
									"type": "boolean",
									"nullable": true,
									"default": false
								}
							}
						}
					}
				},
				"example": {
					"id": "ifi",
					"title_localized": {
						"en": "#1f1e33"
					},
					"artist": "かめりあ(EDP)",
					"bpm": "181",
					"bpm_base": 181,
					"set": "vs",
					"audioTimeSec": 163,
					"side": 1,
					"remote_dl": true,
					"world_unlock": false,
					"date": 1590537604,
					"difficulties": [
						{
							"ratingClass": 0,
							"chartDesigner": "夜浪",
							"jacketDesigner": "望月けい",
							"rating": 5,
							"ratingReal": 5.5
						},
						{
							"ratingClass": 1,
							"chartDesigner": "夜浪",
							"jacketDesigner": "望月けい",
							"rating": 9,
							"ratingReal": 9.2
						},
						{
							"ratingClass": 2,
							"chartDesigner": "夜浪 VS 東星 \"Convergence\"",
							"jacketDesigner": "望月けい",
							"rating": 10,
							"ratingReal": 10.9,
							"ratingPlus": true
						}
					]
				}
			},
			"localization": {
				"required": [
					"en"
				],
				"type": "object",
				"properties": {
					"en": {
						"type": "string",
						"description": "英文本地化信息",
						"default": "No data available"
					},
					"ja": {
						"type": "string",
						"description": "日文本地化信息"
					},
					"ko": {
						"type": "string",
						"description": "韩文本地化信息"
					},
					"zh-Hant": {
						"type": "string",
						"description": "繁体中文本地化信息"
					},
					"zh-Hans": {
						"type": "string",
						"description": "简体中文本地化信息",
						"default": "暂无数据"
					}
				},
				"example": {
					"en": "From over the horizon come three\npowerful new songs from SEGA's arcade\nrhythm game CHUNITHM!\n\nJoin Tairitsu and Chuni Penguin as\nyou take on this monumental challenge!",
					"ja": "地平線の向こうから、\n3つの強力な楽曲がやってくる…！\nSEGAのアーケードリズムゲーム、\nCHUNITHMとのコラボレーション！\n\n対立とチュウニペンギンと共に、\n難敵たちに挑戦しよう！",
					"ko": "3곡의 새로운 음악이\nSEGA의 아케이드 리듬게임 'CHUNITHM'을 통해\n수평선 너머에서 강하게 접근 중!\n\n타이리츠와 츄니펭귄과 함께,\n기념이 될 만한 엄청난 도전에 참여하세요!",
					"zh-Hant": "三首來自世嘉開發的街機節奏遊戲\n《CHUNITHM》的震撼新曲\n已於天際展露鋒芒！\n\n跟隨對立與中二企鵝一起\n共同開始這一系列里程碑式的挑戰！",
					"zh-Hans": "三首来自世嘉开发的街机节奏游戏\n《CHUNITHM》的震撼新曲\n已于天际展露锋芒！\n\n跟随对立与中二企鹅一起\n共同开始这一系列里程碑式的挑战！"
				}
			},
			"arc_ver_link": {
				"type": "object",
				"properties": {
					"ios": {
						"type": "object",
						"properties": {
							"ver": {
								"type": "string"
							},
							"link": {
								"type": "string"
							}
						}
					},
					"android": {
						"type": "object",
						"properties": {
							"ver": {
								"type": "string"
							},
							"link": {
								"type": "string"
							}
						}
					}
				}
			},
			"arc_api_ver": {
				"type": "object",
				"properties": {
					"major": {
						"type": "number",
						"minimum": 0,
						"default": 12
					},
					"prefix": {
						"type": "string",
						"default": "/coffee"
					},
					"host": {
						"type": "string",
						"default": "https://arcapi.lowiro.com"
					}
				},
				"example": {
					"major": 9,
					"prefix": "",
					"host": "https://arcapi.lowiro.com"
				}
			},
			"recent_score": {
				"type": "object",
				"properties": {
					"song_id": {
						"type": "string"
					},
					"difficulty": {
						"type": "number",
						"enum": [
							0,
							1,
							2,
							3
						]
					},
					"score": {
						"type": "number",
						"minimum": 0,
						"maximum": 100000000
					},
					"shiny_perfect_count": {
						"type": "number",
						"minimum": 0
					},
					"perfect_count": {
						"type": "number",
						"minimum": 0
					},
					"near_count": {
						"type": "number",
						"minimum": 0
					},
					"miss_count": {
						"type": "number",
						"minimum": 0
					},
					"clear_type": {
						"type": "number",
						"enum": [
							0,
							1,
							2,
							3,
							4,
							5
						]
					},
					"best_clear_type": {
						"type": "number",
						"enum": [
							0,
							1,
							2,
							3,
							4,
							5
						]
					},
					"health": {
						"type": "number",
						"minimum": 0,
						"maximum": 100
					},
					"time_played": {
						"type": "number"
					},
					"modifier": {
						"type": "number",
						"enum": [
							0,
							1,
							2,
							3,
							4,
							5
						]
					},
					"rating": {
						"type": "number",
						"minimum": 0
					}
				},
				"example": {
					"song_id": "grievouslady",
					"difficulty": 2,
					"score": 0,
					"shiny_perfect_count": 0,
					"perfect_count": 0,
					"near_count": 0,
					"miss_count": 0,
					"clear_type": 0,
					"best_clear_type": 0,
					"health": 0,
					"time_played": 1145141145141,
					"modifier": 0,
					"rating": 0
				}
			},
			"arc_user": {
				"type": "object",
				"properties": {
					"name": {
						"type": "string"
					},
					"user_id": {
						"type": "number",
						"minimum": 1
					},
					"recent_score": {
						"type": "object",
						"$ref": "#/components/schemas/recent_score",
						"nullable": true
					},
					"character": {
						"type": "number",
						"enum": [
							0,
							1,
							2,
							3,
							4,
							6,
							7,
							8,
							9,
							10,
							11,
							12,
							13,
							14,
							15,
							16,
							17,
							18,
							19,
							20,
							21,
							22,
							23,
							24,
							25,
							26,
							27,
							28,
							29,
							30,
							31,
							32,
							33,
							34,
							35,
							36
						]
					},
					"join_date": {
						"type": "number"
					},
					"rating": {
						"type": "number"
					},
					"is_skill_sealed": {
						"type": "boolean"
					},
					"is_char_uncapped": {
						"type": "boolean"
					},
					"is_char_uncapped_override": {
						"type": "boolean"
					},
					"is_mutual": {
						"type": "boolean"
					}
				},
				"example": {
					"user_id": 114514,
					"name": "114514",
					"recent_score": {
						"song_id": "grievouslady",
						"difficulty": 2,
						"score": 0,
						"shiny_perfect_count": 0,
						"perfect_count": 0,
						"near_count": 0,
						"miss_count": 0,
						"clear_type": 0,
						"best_clear_type": 0,
						"health": 0,
						"time_played": 1145141145141,
						"modifier": 0,
						"rating": 0
					},
					"character": 0,
					"join_date": 1145141145141,
					"rating": 0,
					"is_skill_sealed": false,
					"is_char_uncapped": false,
					"is_char_uncapped_override": false,
					"is_mutual": false
				}
			},
			"usercode": {
				"type": "string",
				"minLength": 9,
				"maxLength": 9,
				"example": "012345678"
			},
			"difficulty": {
				"oneOf": [
					{
						"type": "string",
						"enum": [
							"pst",
							"prs",
							"ftr",
							"byn",
							"past",
							"present",
							"future",
							"beyond"
						]
					},
					{
						"type": "number",
						"enum": [
							0,
							1,
							2,
							3
						]
					}
				]
			},
			"best_score": {
				"type": "object",
				"properties": {
					"song_id": {
						"type": "string"
					},
					"difficulty": {
						"type": "number",
						"enum": [
							0,
							1,
							2,
							3
						]
					},
					"score": {
						"type": "number",
						"minimum": 0,
						"maximum": 100000000
					},
					"shiny_perfect_count": {
						"type": "number",
						"minimum": 0
					},
					"perfect_count": {
						"type": "number",
						"minimum": 0
					},
					"near_count": {
						"type": "number",
						"minimum": 0
					},
					"miss_count": {
						"type": "number",
						"minimum": 0
					},
					"clear_type": {
						"type": "number",
						"enum": [
							0,
							1,
							2,
							3,
							4,
							5
						]
					},
					"best_clear_type": {
						"type": "number",
						"enum": [
							0,
							1,
							2,
							3,
							4,
							5
						]
					},
					"health": {
						"type": "number",
						"minimum": 0,
						"maximum": 100
					},
					"time_played": {
						"type": "number"
					},
					"modifier": {
						"type": "number",
						"enum": [
							0,
							1,
							2,
							3,
							4,
							5
						]
					},
					"rating": {
						"type": "number",
						"minimum": 0
					},
					"is_skill_sealed": {
						"type": "boolean",
						"default": false
					},
					"is_char_uncapped": {
						"type": "boolean",
						"default": false
					}
				},
				"example": {
					"song_id": "grievouslady",
					"difficulty": 2,
					"score": 0,
					"shiny_perfect_count": 0,
					"perfect_count": 0,
					"near_count": 0,
					"miss_count": 0,
					"health": 0,
					"modifier": 0,
					"time_played": 114514145141,
					"best_clear_type": 0,
					"clear_type": 0,
					"character": 0,
					"is_skill_sealed": false,
					"is_char_uncapped": false,
					"rating": 0.0000
				}
			}
		}
	}
}